// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FocusController from "./focus_controller"
application.register("focus", FocusController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RemoveController from "./remove_controller"
application.register("remove", RemoveController)

import SlideOverController from "./slide_over_controller"
application.register("slide-over", SlideOverController)
