# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-and-test: 
    # executor: node/default
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/ruby:3.2.2
        environment:
          NODE_ENV: test 
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: postgres
      - image: circleci/postgres:13.3
        environment: 
          POSTGRES_USER: postgres
          POSTGRES_DB: blogger_test
          POSTGRES_HOST_AUTH_METHOD: trust
    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      # This is the version of Node.js to use not 16
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18' 
      - run: echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
      - run: source $BASH_ENV && gem install bundler
      - run: bundle install
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bin/rails db:{create,migrate} --trace
      - run:
          name: Run rspec in parallel 
          command: bundle exec rspec
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test_results
      - run:
          name: Precompile Assets
          command: bundle exec rake assets:precompile
  yarn_install:
    docker:
      - image: circleci/ruby:3.2.2-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-v1-{{ checksum "yarn.lock" }}
            - yarn-cache-v1-
      - run: yarn install --cache-folder ~/.cache/yarn
      - run: bundle exec rake assets:precompile
      - save_cache:
          key: yarn-cache-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  deploy: 
    executor: heroku/default
    steps:
      - attach_workspace:
          at: ~/projects/blogger
      - heroku/deploy-via-git:
          force: true
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows

workflows:
  build-and-test:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          force: true
          requires:
            - build-and-test
          post-steps:
              - run: 
                  name: migrate 
                  command: heroku run -a $HEROKU_APP_NAME rake db:migrate
          filters:
            branches:
              only:
                - main